name: Terraform CI/CD Pipeline

on:
  workflow_call:

env:
    TF_INPUT: true
    TF_IN_AUTOMATION: true
    TF_LOG: INFO
    TF_VAR_aws_instance_count: ${{ vars.aws_instance_count }}
    TF_VAR_billing_code: ${{ vars.billing_code }}
    TF_VAR_vpc_cidr_block: ${{ vars.vpc_cidr_block }}
    TF_VAR_vpc_subnet_count: ${{ vars.vpc_subnet_count }}
    TF_VAR_vpc_subnet_mask: ${{ vars.vpc_subnet_mask }}
    TF_VAR_project: ${{ vars.project }}
    TF_VAR_company: ${{ vars.company }}
    TF_VAR_region: ${{ vars.aws_region }}
    TF_VAR_node_desired_capacity: ${{ vars.node_desired_capacity }}
    TF_VAR_node_maximum_capacity: ${{ vars.node_maximum_capacity }}
    TF_VAR_node_minumum_capacity: ${{ vars.node_minumum_capacity }}
    TF_VAR_eks_version: ${{ vars.eks_version }}

jobs:
  plan_and_apply:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Show Inputs
        run: |
          echo "Region: $TF_VAR_region"
          echo "Billing Code: $TF_VAR_billing_code"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ vars.SESSION_NAME }}
            aws-region: ${{ vars.aws_region }}
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Terraform Setup and Apply
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./deployment/terraform/terraform-provision-ekscluster-use-case-1
        run: | 
            terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="region=${{ vars.backend_region }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}"

      - name: Terraform Format
        id: format
        run: terraform fmt -check

      - name: Terraform Workspace
        id: workspace
        run: |
            set -e
            WORKSPACE="${{ vars.workspace_name }}"
            if terraform workspace list | grep -q "\b$WORKSPACE\b"; then
                terraform workspace select "$WORKSPACE"
            else
                terraform workspace new "$WORKSPACE"
            fi 
      
      - name: Terraform Validate
        id: validate
        if: (success() || failure())
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./deployment/terraform/terraform-provision-ekscluster-use-case-1

      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: terraform apply -auto-approve
        working-directory: ./deployment/terraform/terraform-provision-ekscluster-use-case-1    
