name: Terraform CI/CD Pipeline

on:
  workflow_call:
    inputs:
        <<: *common_inputs
    secrets:
        <<: *secrets

env:
    <<: *env

jobs:
  plan_and_apply:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            role-session-name: ${{ vars.SESSION_NAME }}
            aws-region: ${{ inputs.aws_region }}
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Terraform Setup and Apply
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./deployment/terraform/terraform-provision-ekscluster-use-case-1
        run: | 
            terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="region=${{ inputs.backend_region }}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}"

      - name: Terraform Format
        id: format
        run: terraform fmt -check

      - name: Terraform Workspace
        id: workspace
        run: |
            set -e
            WORKSPACE="${{ inputs.workspace_name }}"
            if terraform workspace list | grep -q "\b$WORKSPACE\b"; then
                terraform workspace select "$WORKSPACE"
            else
                terraform workspace new "$WORKSPACE"
            fi 
      
      - name: Terraform Validate
        id: validate
        if: (success() || failure())
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./deployment/terraform/terraform-provision-ekscluster-use-case-1

      - name: Terraform Apply
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: terraform apply -auto-approve
        working-directory: ./deployment/terraform/terraform-provision-ekscluster-use-case-1    
